# ---------- Build Stage ----------
FROM node:22-alpine AS builder

WORKDIR /app

COPY node/package*.json ./

RUN npm ci

COPY node/ .

RUN npm run build


# ---------- Production Stage ----------
FROM node:22-alpine

WORKDIR /app

COPY node/package*.json ./

RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

ENTRYPOINT ["node"]

CMD ["dist/index.js"]